package lv.bootcamp.shelter.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

// Generated by GitHub Copilot
/**
 * JPA entity representing a shelter animal.
 * Used in @DataJpaTest exercises to verify persistence and query behavior.
 */
@Entity
@Table(name = "animals")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Animal {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AnimalType type;

    private String breed;

    private Integer age;

    private String description;

    // Nullable but unique when present — not every animal is chipped yet.
    // Target of the ANIMAL-3 constraint test (AnimalRepositoryTest).
    @Column(unique = true)
    private String microchipId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AnimalStatus status;
}
